# Header
menu:
  首页: /
  手游: categories/game
  技术: categories/tool
  杂项: categories/other
  感悟: categories/life
  标签: /tags
  归档: archives
  关于: /about

# Content
excerpt_link: 阅读更多
content_max_width: 1000px

# Sidebar
author:
  name: Asroads
  work: Web Developer &amp; Coder
  location: BeiJing, China
  avatar_url: /images/avatar.jpg

# Links:
links:
  - svg: ./source/svg/github.svg
    url: https://github.com/asroads
  - svg: ./source/svg/more.svg
    url: https://github.com/jsroads
  - svg: ./source/svg/twitter.svg
    url: https://www.jianshu.com/u/7eeaddb5cb20


# # github comment 
# git_commit:
#   enable: true
#   client_id: 7fbe80427f54741e289f
#   client_secret: f34ed5fd92e54c9000bd37ba951948cb939deff5
#   repo: sanonz.github.io
#   owner: sanonz
#   admin:
#     - sanonz
#   per_page: 10
# 
# 
# # 百度统计
# baidu:
#   id: e4027971a230b210f4671f485b33846a

# Miscellaneous
rss: /atom.xml
favicon: /images/favicon.ico
