# Header
menu:
  首页: /
  手游: categories/game
  技术: categories/tool
  杂项: categories/other
  感悟: categories/life
  标签: javascript:;
  归档: archives
  关于: /about

# Content
excerpt_link: 阅读更多

# Sidebar
author:
  name: Asroads
  work: Web Developer &amp; Coder
  location: BeiJing, China
  avatar_url: /images/avatar.jpg

links:
  github: https://github.com/asroads
  more: https://github.com/asroads
  twitter: https://www.jianshu.com/u/7eeaddb5cb20

# widgets:
# - category
# - tag
# - tagcloud
# - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
# index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
# show_count: false
# archive_type: 'monthly'

# Disqus 
disqus:
  enable: true
  shortname: asroads    #your name
  count: true

# 友盟统计
umeng:
  prefix: s13
  id: 1234567890

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
